Flight details

In [1]:
data = {'Customer name':['Alex', 'Brad', 'Chris', 'Dan','Elsi','Fash','Gilma'],
        'Seat Numbers':[1,12,23,41,65,62,78],
        'Number of Family members' :[2,1,0,3,4,4,3]
}
import pandas as pd
df = pd.DataFrame(data)

df.sample(3)

  Customer name  Seat Numbers  Number of Family members
1          Brad            12                         1
3           Dan            41                         3
0          Alex             1                         2

In [4]:
sports_data = sports_data = {
    "name": [
        "Serena Williams", "Usain Bolt", "Lionel Messi", "PV Sindhu", "Michael Phelps",
        "Virat Kohli", "Simone Biles", "Novak Djokovic", "Katie Ledecky", "Roger Federer",
        "Neeraj Chopra", "Cristiano Ronaldo", "Mary Kom", "Saina Nehwal", "M S Dhoni",
        "Sun Yang", "Rafael Nadal", "Eliud Kipchoge", "Deepika Kumari", "Sachin Tendulkar"
    ],
    "category": [
        "Tennis", "Athletics", "Football", "Badminton", "Swimming",
        "Cricket", "Gymnastics", "Tennis", "Swimming", "Tennis",
        "Athletics", "Football", "Boxing", "Badminton", "Cricket",
        "Swimming", "Tennis", "Athletics", "Archery", "Cricket"
    ],
    "cash_award": [
        250000, 300000, 500000, 200000, 350000,
        400000, 270000, 260000, 230000, 300000,
        220000, 480000, 210000, 190000, 380000,
        240000, 270000, 290000, 160000, 450000
    ]
}

import pandas as pd
df = pd.DataFrame(sports_data)
Stratified_Sample = df.groupby('category').apply(lambda x: x.sample(min(len(x), 3)))
print(Stratified_Sample)

                            name    category  cash_award
category
Archery    18     Deepika Kumari     Archery      160000
Athletics  17     Eliud Kipchoge   Athletics      290000
           1          Usain Bolt   Athletics      300000
           10      Neeraj Chopra   Athletics      220000
Badminton  3           PV Sindhu   Badminton      200000
           13       Saina Nehwal   Badminton      190000
Boxing     12           Mary Kom      Boxing      210000
Cricket    19   Sachin Tendulkar     Cricket      450000
           14          M S Dhoni     Cricket      380000
           5         Virat Kohli     Cricket      400000
Football   11  Cristiano Ronaldo    Football      480000
           2        Lionel Messi    Football      500000
Gymnastics 6        Simone Biles  Gymnastics      270000
Swimming   8       Katie Ledecky    Swimming      230000
           15           Sun Yang    Swimming      240000
           4      Michael Phelps    Swimming      350000
Tennis     0     Serena Williams      Tennis      250000
           16       Rafael Nadal      Tennis      270000
           7      Novak Djokovic      Tennis      260000

/tmp/ipython-input-4-2409336737.py:24: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  Stratified_Sample = df.groupby('category').apply(lambda x: x.sample(min(len(x), 3)))